steps:
# This step build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/dbt-demo:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/dbt-demo:$SHORT_SHA'

# This step run the integration test
- name: 'gcr.io/$PROJECT_ID/dbt-demo:$SHORT_SHA'
  id: Test
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - '/dbt/dbt_run.sh test'

  